export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_PRODUCTS_ON_PAGE = 'SET_PRODUCTS_ON_PAGE';
export const SET_PRODUCT_ON_PAGE = 'SET_PRODUCT_ON_PAGE';
